---
- name: Docker Environment
  hosts: linux
  tasks:
 
  - name: Create a Docker directory if it does not exist
    file:
      path: /opt/docker
      state: directory
      mode: '0755'

  - name: Copy DockerFile
    copy:
      src: /root/ansible/Dockerfile
      dest: /opt/docker/Dockerfile

  - name: Install pip
    yum: 
      name: python2-pip 
      state: present
      
  - name: install docker-py
    pip: 
      name: docker-py
      
  - name: Build Docker image from Dockerfile
    docker_image:
      name: web
      build: 
        dockerfile: /opt/docker/Dockerfile
      state: present
      source: build 
        
  - name: Running the container
    docker_container:
      image: web:latest
      path: docker
      state: running

  - name: Check if container is running
    shell: docker ps
